import 'package:awurudu/window/windows.dart';

class ItemList {
  static final List<CardsonWindow> itemList = [
    const CardsonWindow(
      2024,
      04,
      11,
      08,
      00,
      imageBack: "assets/download.png",
      date: "2024.04.11",
      title: "නව සද බැලීම",
      visible: false,
      cloth:"" ,
      dir: "",
      eat: "",
    ),
    const CardsonWindow(
      2024,
      04,
      11,
      08,
      00,
      imageBack: "assets/bath.png",
      date: "2024.04.11",
      title: "පරන අවුරුද්දේ ස්නානය",
      visible: false,
      cloth:"" ,
      dir: "",
      eat: "",
    ),
    const CardsonWindow(
      2024,
      04,
      13,
      21,
      05,
      imageBack: "assets/udawa.png",
      date: "2024.04.13 - 09.05 PM",
      title: "අලුත් අවුරුදු උදාව",
      visible: false,
      cloth:"" ,
      dir: "",
      eat: "",
    ),
    const CardsonWindow(
      2024,
      04,
      13,
      14,
      41,
      imageBack: "assets/punya.png",
      date: "2024.04.13 - 02.41 PM",
      title: "පුන්‍ය කාලය",
      visible: false,
      cloth:"" ,
      dir: "",
      eat: "",
    ),
    const CardsonWindow(
      2024,
      04,
      13,
      23,
      06,
      imageBack: "assets/ahara.png",
      date: "2024.04.13 - 11.06 PM",
      title: "අහාර පිසිම",
      visible: true,
      cloth:"නිල් පැහැ වස්ත්‍රාභරනයෙන් සැරසී" ,
      dir: "දකුණු දිශාව බලා",
      eat: "උක් හකුරු මිශ්‍ර කිරිබතක් හා කැවිලි",
    ),
    const CardsonWindow(
      2024,
      04,
      14,
      00,
      06,
      imageBack: "assets/wada.png",
      date: "2024.04.14 - 00.06 AM",
      title: "වැඩ අල්ලා ගනුදෙනු කිරිම හා ආහර අනුභවය",
      visible: true,
      cloth:"නිල් පැහැ වස්ත්‍රාභරනයෙන් සැරසී" ,
      dir: "දකුණු දිශාව බලා",
      eat: "ගිතෙල් හා උක් හකුරු මිශ්‍ර කිරිබතක් හා කැවිලි ",
    ),
    const CardsonWindow(
      2024,
      04,
      15,
      10,
      17,
      imageBack: "assets/thel.png",
      date: "2024.04.15 - 10.17 AM",
      title: "හිස තෙල් ගෑම",
      visible: true,
      cloth:"සුදු පැහැ වස්ත්‍රාභරනයෙන් සැරසී" ,
      dir: "දකුණු දිශාව බලා",
      eat: "හිසට දියුල් පත්,පයට ඉම්බුල් පත්,දියුල් පත් මිශ්‍ර නානු තෙල්",
    ),
    const CardsonWindow(
      2024,
      04,
      17,
      06,
      52,
      imageBack: "assets/rakiyawa.png",
      date: "2024.04.17 - 06.52 AM",
      title: "රැකිරක්ශා සදහා පිටවිම",
      visible: true,
      cloth:"කොල පැහැ වස්ත්‍රාභරනයෙන් සැරසී" ,
      dir: "උතුර දිශාව බලා",
      eat: "ගිතෙල් හා උඛකුරු මිශ්‍ර කිරිබතක් හා කැවිලි ",
    ),
    const CardsonWindow(
      2024,
      04,
      17,
      10,
      16,
      imageBack: "assets/pala.png",
      date: "2024.04.17 - 10.16 PM",
      title: "පැල සිටවීම",
      visible: true,
      cloth:"රන්වන් වස්ත්‍රාභරනයෙන් සැරසී" ,
      dir: "නැගෙනහිර දිශාව බලා",
      eat: "",
    ),
  ];
}